# Abstract {#Abstract}

Die Beispielanalyse gliedert sich wie folgt:

-   [**Setup und Daten**](#SetupDaten): Ich verwende hier [R-Markdown-Dateien](#R-Markdown), die neben Fließtext auch Codechunks und deren Output beinhalten. So können Sie mich und meine Arbeitsweise besser kennenlernen. Bei den [Daten](#Daten) handelt es sich um Bewertungen und Reviews, die **Obi-Kunden** in den letzten Wochen auf www.trustedshops.de hinterlassen haben. Diese Daten werden mit Hilfe eines modernen [Large Language Models](#LLM) ausgewertet.

-   [**Reviews und Bewertungen**](#ReviesBewertungen): In einem ersten Analyseschritt wird die Beziehung zwischen den Reviews und den Bewertungen mit konventionellen statistischen Methoden untersucht. Im Ergebnis lässt sich ein Zusammenhang zwischen dem [Textumfang](#Textumfang) und den Bewertungen aufzeigen. So sind die unzufriedenen Kunden im Textmaterial überrepräsentiert (Abb.\@ref(fig:TextBew)). Je niedriger die Kundenzufriedenheit ist, desto länger sind auch die Texte (Abb.\@ref(fig:TextlaengeBew)). Die Kundenreviews bilden als unstrukturierte Daten eine große sprachliche Vielfalt ab. Diese Vielfalt wird durch eine Hauptkomponentenanalyse ausgewertet. Im Ergebnis zeigt dieses Verfahren des unüberwachten maschinellen Lernens, dass die semantische [Varianz](#Varianz) am besten durch die Kundenzufriedenheit erklärt werden kann (Abb.\@ref(fig:PCA)).

-   [**Aussagen und Themen**](#AussagenThemen): Eine Kundenreview kann Aussagen zu unterschiedlichen Themen beinhalten. Daher werden die Reviews für den zweiten Analyseschritt in unterschiedliche Aussagen aufgesplittet. Diese Aussagen werden anschließend durch verschiedene Methoden des maschinellen Lernens ausgewertet. Dabei handelt es sich zum einen um das unüberwachte, explorative [Topic Modelling](#TopMod). Im Ergebnis zeigt dies ein für die gesamte Datenserie optimales Modell. So lassen sich die Themen aus der Kundenperspektive heraus entwickeln. Im vorliegenden Anwendungsfall werden beispielsweise für Kunden bedeutsame Erlebnisse, wie das Warten oder eine schnelle und einfache Abwicklung als Cluster herausgestellt (Abb. \@ref(fig:TopMod)). Das Warten ist ein Aspekt, den Kunden in verschiedenen Phasen ihrer Customer Journey erleben können. Eine isolierte Betrachtung dieser Phasen ist für Entscheidungsträger typischerweise nützlich, da sich nur so ermitteln lässt, wo Verbesserungspotenzial besteht. Aufgrund dessen beinhaltet diese Beispielanalyse zum anderen eine konfirmatorische Themenanalyse. Dabei handelt es sich um eine [semantische Suche](#SemSu), die hier als Zero-Shot-Learning implementiert ist. Dessen Ergebnisse deuten darauf hin, dass insbesondere die Liefergeschwindigkeit ein Thema ist, das die Kunden beschäftigt (siehe Abbildung \@ref(fig:PropPosNeg)). 
